import { Note } from "@/lib/notes";
import Head from "next/head";
import { useEffect, useState } from "react";
import { NoteCard } from "../components/NoteCard";

export default function Home() {
  const [notes, setNotes] = useState<Note[]>([]);

  useEffect(() => {
    fetch("/api/notes")
      .then((response) => response.json())
      .then((res) => setNotes(res.data));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">Minhas notas</h1>
        <div className="flex flex-col gap-4 ">
          {notes.map((note) => (
            <NoteCard title={note.title} content={note.content} />
          ))}
        </div>
      </main>
    </>
  );
}
